version: '3.8'

services:
  frontend:
    build:
      context: ./stock-event-analyzer-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
    networks:
      - stock-event-network

  backend:
    build:
      context: ./stock-event-analyzer-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      # You'll need to provide these values via an .env file or when running docker-compose
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      # Mount the .env file for backend credentials
      - ./stock-event-analyzer-backend/.env:/app/.env
    networks:
      - stock-event-network

networks:
  stock-event-network:
    driver: bridge 