version: '3.8'

services:
  frontend:
    build:
      context: ./stock-event-analyzer-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - fastapi
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
      - NEXT_PUBLIC_FASTAPI_URL=http://fastapi:8000
      - NODE_ENV=development
    volumes:
      - ./.env:/app/.env
      - ./stock-event-analyzer-frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - stock-event-network
    command: npm run dev

  backend:
    build:
      context: ./stock-event-analyzer-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./.env:/app/.env
      - ./stock-event-analyzer-backend:/app
      - /app/node_modules
    networks:
      - stock-event-network
    command: npm run dev

  fastapi:
    build:
      context: ./stock-event-analyzer-fastapi
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./.env:/app/.env
      - ./stock-event-analyzer-fastapi:/app
    networks:
      - stock-event-network
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

networks:
  stock-event-network:
    driver: bridge 